# Taken from https://github.com/banool/team_heist_tactics/blob/master/.github/filters.yml
force: &force
  - ".force"

ci: &ci
  - ".github/**/*"

frontend:
  - *force
  - 'frontend/lib/**'
  - 'site/**'

driver:
  - *force
  - 'driver/**'

move:
  - *force
  - 'move/**'
