[package]
name = "AptosInfiniteJukebox"
version = "0.2.1"
upgrade_policy = "compatible"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'testnet'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.DataStructure]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'banool/iterable_table_dport'
subdir = 'aptos-move/move-examples/data_structures'

[addresses]
jukebox = "0xb078d693856a65401d492f99ca0d6a29a0c5c0e371bc2521570a86e40d95f823"
dport_collections = "0xb078d693856a65401d492f99ca0d6a29a0c5c0e371bc2521570a86e40d95f823"
