name: aptos_infinite_jukebox
description: An Infinite Jukebox powered by Aptos

version: 1.0.104+105

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  aptos_sdk_dart:
  built_value:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http:
  settings_ui:
  shared_preferences:
  spotify:
  spotify_sdk:
  url_launcher:

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^1.1.7
  integration_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon512.png"

flutter:
  uses-material-design: true