name: aptos_infinite_jukebox
description: An Infinite Jukebox powered by Aptos

version: 1.0.75+76

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http:
  spotify_sdk:
  shared_preferences:
  settings_ui:
  url_launcher:
  aptos_sdk_dart:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  icons_launcher: ^1.1.7
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon512.png"

flutter:
  uses-material-design: true