name: CI

on:
  push:
    branches: [ main ]

jobs:
  buildandroid:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.10.5'
        channel: stable

    # Initial build and test
    - run: flutter pub get

    # Run tests
    - run: flutter test

    # Build the web frontend
    - run: flutter build web

    # Zip up the build
    # TODO: Confirm zip is available
    # TODO: See whether the below step just zips it for you
    - run: zip -r web-release.zip build/web

    # Make a release with the web build
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "latest web build"
        files: web-release.zip