name: Build and publish Android build

on:
  push:
    branches: [ main ]

jobs:
  build_android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aptos_infinite_jukebox
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: '15'

    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.10.5'
        channel: stable

    - run: flutter pub get

    - run: flutter test

    - run: flutter build appbundle

    # Sign release
    - name: Sign Android release
      id: sign_release
      uses: r0adkll/sign-android-release@v1
      with:
          releaseDirectory: build/app/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: key
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

    # Publish release
    - name: Publish Android build to internal track
      uses: r0adkll/upload-google-play@v1.0.15
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: com.example.aptos_infinite_jukebox
        # releaseFile: ${{ steps.run_tests.outputs.signedReleaseFile }}
        releaseFile: build/app/outputs/bundle/release/app-release.aab
        track: internal
